### ISSUE TITLE
Fouc

### ISSUE THREAD

**Issue by marathon67** [iwamatsu0430/WebSlidesAnimation#1]
First, thanks a lot for your extension. I find it very usefull. But I have a little problem with it. When I display a section using animate-show for the second (or more) time, the hidden content is shown for a couple of seconds, before it disappears. Here is the code of my section :

```
<section>  <!-- slide 05 -->  
          <!-- Overlay/Opacity: [class*="bg-"] > .background.dark or .light -->  
          <span data-step-count=1></span>  
          <span class="background" style="background-image:url('static/images/ayers_rock.jpg')"></span>  
          <div class="wrap">  
            <div class="content-left bg-trans-dark fadeInUp animate-show" data-step=1>  
              <h2><strong>Projet Ornithorynque</strong></h2>  
              <p>Découvrez ici les travaux des élèves de CP de la classe de Madame Marckert ... après les congés d'été.</p>  
            </div>  
          </div>  
          <!-- .end .wrap -->  
</section>
 ```

You can see the whole test site at https://github.com/marathon67/platypus

Any idea on how to avoid that flash of unstyled content ?

**Comment by iwamatsu0430** [comment]
Thanks a lot for using my extension. I could see a problem my environment.
Maybe extension logic is not good. As I resolve this problem, please can you wait for fix?

**Comment by marathon67** [comment]
I shall wait... The issue is not very important and does prevent using your extension.

**Comment by iwamatsu0430** [comment]
@marathon67 Hi, I released fixed extension. could you please check?
![result](https://user-images.githubusercontent.com/3608976/30674057-55eafea4-9eb2-11e7-8cfa-7758ed9253e5.gif)

**Comment by marathon67** [comment]
Thanks a lot for that promp update. I shall test it ASAP.

**Comment by marathon67** [comment]
I have tested your correction. Now it works perfectly. _Bravo_ as we say in french...
